
# Installation instructions for roplspvs (Ropls-with-permutated-variable-selection)
#This package was created for r 3.6.2 using rstudio 1.1.463 but has been tested
#for R 3.6.2, 4.0.0, 4.0.3, 4.0.5, 4.1.2 and 4.3.0

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
if (!requireNamespace("ropls", quietly = TRUE))
BiocManager::install("ropls")
if (!requireNamespace("tools", quietly = TRUE))
install.packages("tools")
if (!requireNamespace("ggplot2", quietly = TRUE))
install.packages("ggplot2")
if (!requireNamespace("ggrepel", quietly = TRUE))
install.packages("ggrepel")
if (!requireNamespace("kableExtra", quietly = TRUE))
install.packages("kableExtra")
if (!requireNamespace("gridExtra", quietly = TRUE))
install.packages("gridExtra")
if (!requireNamespace("ggpubr", quietly = TRUE))
install.packages("ggpubr")
if (!requireNamespace("matrixStats", quietly = TRUE))
install.packages("matrixStats")
if (!requireNamespace("stringr", quietly = TRUE))
install.packages("stringr")
if (!requireNamespace("tryCatchLog", quietly = TRUE))
install.packages("tryCatchLog")
if (!requireNamespace("devtools", quietly = TRUE))
install.packages("devtools")
if (!requireNamespace("DescTools", quietly = TRUE))
install.packages("DescTools")
if (!requireNamespace("precrec", quietly = TRUE))
install.packages("precrec")
if (!requireNamespace("pROC", quietly = TRUE))
install.packages("pROC")
if (!requireNamespace("rstatix", quietly = TRUE))
install.packages("rstatix")
if (!requireNamespace("rmarkdown", quietly = TRUE))
install.packages("rmarkdown")
