---
output:
  html_document:
    toc: true
    toc_depth: 3
    number_sections: true
mathjax: null

---

---
#title: |
#    | Model strategy 1
    
author: |
    | Ropls with permutated variable selection: Version 0.13.0
    | Marika Strom
---

# Model strategy 1. Models with userset p(corr) cutoff during variable selection and userset number of orthogonal variables pre and post variable selection

### Model descripton
Model post variable selection using p(corr) cutoff `r paste(pcorr); if(pcorr_Model1=="according to p-value"){paste(" which correspond to p-value ", p_pearson_of_pcorr_cutoff)}` and has `r ortho_pre_vs_Model1` orthogonals in model pre variable selection and `r ortho_post_vs_Model1` orthogonals in model post variable selection


```{R Model1}

ortho_pre_vs <- ortho_pre_vs_Model1
ortho_post_vs <- ortho_post_vs_Model1

testvariablename <- "result_Model1"
testvariable <- exist_in_rdata(testvariablename, filename_rdata, directory_output_reports, directory_and_filename_rdata)
if (!is.null(testvariable)) {
  result_Model1 <- testvariable
} else {
  result_Model1 <-
    opls_model_with_variable_selection_trycatch(
      subsetdatamatrix,
      ortho_pre_vs,
      ortho_post_vs,
      class = classordered,
      pcorr, printoptmodel = "none",
      plotoptmodel = "none",
      no_permutations_post_vs = no_permutations_post_vs_selected_models,
      variable_selection_using_VIP,
      max_no_of_ortho_pre_vs, 
      max_no_of_ortho_post_vs
    )
}
```
### Model pre variable selection

```{R plot model pre vs model1}
result_pre_vs <- result_Model1$beforevsdata.oplsda@summaryDF
colnames(result_pre_vs)[6] <- "ortho pre v.s."
kable(result_pre_vs, row.names = T) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```

### Model statistics

```{R plot result model1}

kable(result_Model1$resultaftervs, row.names = T) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

plot(result_Model1$aftervsdata.oplsda, typeVc = c("overview"))

if (ortho_post_vs > 0) {
  plot(result_Model1$aftervsdata.oplsda, typeVc = c("outlier"))
}
```

### Score plots

```{R plot score model1}

if (ortho_post_vs > 0) {
  plot(result_Model1$aftervsdata.oplsda, typeVc = c("x-score"))
}

plotscore(result_Model1, classordered)

plotboxplot(result_Model1, subsetsampleID, colname_groupID, classordered)
```

### Loading plots

```{R plot loading model1}

if (ortho_post_vs > 0) {
  plot(result_Model1$aftervsdata.oplsda, typeVc = c("x-loading"))
}

plotpcorr(result_Model1, variable_names_length, variable_names_position)

if (length(result_Model1$pcorrlistaftervs$pcorrlistaftervs) >= 50) {
  plotpcorronly50variables(result_Model1, variable_names_length, variable_names_position)
}
```

### Permutation after variable selection

```{R plot perm post vs model1}

plot(result_Model1$aftervsdata.oplsda, typeVc = c("permutation"))
```

### Permutation including variable selection
Subjects were permutated and variable selection performed using p(corr) cutoff `r pcorr` corresponding to p-value `r p_pearson_of_pcorr_cutoff`,  with `r ortho_pre_vs_Model1` orthogonal variables in model pre varibale selection and `r ortho_post_vs_Model1` orthogonal variables in model post variable selection

#### Table of permutation

```{R permutation over vs of model1}

testvariablename <- "permutated_models_Model1"
testvariable <- exist_in_rdata(testvariablename, filename_rdata, directory_output_reports, directory_and_filename_rdata)
if (!is.null(testvariable)) {
  permutated_models_Model1 <- testvariable
} else {
  permutated_models_Model1 <-
    table_of_randomised_models_over_vs(
      subsetsampleID,
      colname_groupID,
      subsetdatamatrix,
      ortho_pre_vs,
      ortho_post_vs,
      class = classordered,
      pcorr,
      no_permutations_over_vs,
      variable_selection_using_VIP, 
      max_no_of_ortho_pre_vs, 
      max_no_of_ortho_post_vs
    )
}

for (l in 1:nrow(permutated_models_Model1)) {
  if (is.na(permutated_models_Model1$`Q2(cum)`[l]) | permutated_models_Model1$`Q2(cum)`[l] < (-1)) {
    permutated_models_Model1$`Q2(cum)`[l] <- 0
  }
}

kable(permutated_models_Model1) %>%
  kable_styling() %>%
  scroll_box(width = "fullwidth", height = "300px")
```

 
#### Percentage of R2 and Q2 in permutated model larger than R2 and Q2 in unpermutated model

```{R}


percent_R2_and_Q2_in_permutated_larger_than_in_unpermutated_Model1 <-
  percent_R2_and_Q2_in_permutated_larger_than_in_unpermutated(
    permutated_models_Model1,
    result_Model1$resultaftervs$`R2Y(cum)`,
    result_Model1$resultaftervs$`Q2(cum)`
  )

pvalue_R2_and_Q2_in_perm_Model1 <-
  pvalue_R2_and_Q2_in_perm(
    permutated_models_Model1,
    result_Model1$resultaftervs$`R2Y(cum)`,
    result_Model1$resultaftervs$`Q2(cum)`
  )

percentage_and_pvalue_perm_Model1 <- as.data.frame(cbind(percent_R2_and_Q2_in_permutated_larger_than_in_unpermutated_Model1, row.names(pvalue_R2_and_Q2_in_perm_Model1), pvalue_R2_and_Q2_in_perm_Model1[, 1]))

colnames(percentage_and_pvalue_perm_Model1) <- NULL
kable(percentage_and_pvalue_perm_Model1, row.names = T) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

#### Plot of permutations including variable selection

```{R  plot permutation over vs Model1, fig.width = 10}

plotpermutationswithoriginalmodelandreg(permutated_models_Model1, subsetdatamatrix, ortho_pre_vs, ortho_post_vs, class = classordered, pcorr, variable_selection_using_VIP)

pcorr <- calculatepcorrfrompvalue(selectpvalue = p_pearson_of_pcorr_cutoff, n = nrow(subsetsampleID))

```
