---
output:
  html_document:
    toc: true
    toc_depth: 3
    number_sections: true
mathjax: null

---

---
#title: |
#    | Model strategy 2
    
author: |
    | Ropls with permutated variable selection: Version 0.13.0
    | Marika Strom
---

# Model strategy 2. Model with p(corr) cutoff corresponding to a p-value cutoff set by user

Selecting model with variable selection using p(corr) cutoff `r pcorr` corresponding to p-value `r p_pearson_of_pcorr_cutoff`

## Optimizing model

### Selecting amount of orthogonal variables in model pre variable selection and in model post variable selection

#### Table of model post variable selection with different amount of orthogonal variables in model pre variable selection and in model post variable selection 


```{R table of orthogonals model post vs Model2}
result_Model2_test <-
    opls_model_with_variable_selection_trycatch(
      subsetdatamatrix,
      ortho_pre_vs=NA,
      ortho_post_vs=NA,
      class = classordered,
      pcorr, printoptmodel = "none",
      plotoptmodel = "none",
      no_permutations_post_vs = 0,
      variable_selection_using_VIP,
      max_no_of_ortho_pre_vs,
      max_no_of_ortho_post_vs
    )

testvariablename <- "model_post_vs_table_with_different_amount_of_ortho_pre_and_post_vs_Model2"
testvariable <- exist_in_rdata(testvariablename, filename_rdata, directory_output_reports, directory_and_filename_rdata)
if (!is.null(testvariable)) {
  model_post_vs_table_with_different_amount_of_ortho_pre_and_post_vs_Model2 <- testvariable
} else {
  model_post_vs_table_with_different_amount_of_ortho_pre_and_post_vs_Model2 <-
    model_post_vs_table_with_different_amount_of_ortho_pre_and_post_vs(
      subsetdatamatrix,
      no_of_orthogonal_in_model_pre_vs = result_Model2_test$resultaftervs$`ortho pre v.s.`,
      no_of_orthogonal_in_model_post_vs = result_Model2_test$resultaftervs$`ortho post v.s.`,
      class = classordered,
      pcorr = pcorr,
      no_permutations_post_vs = no_permutations_post_vs,
      variable_selection_using_VIP,
      max_no_of_ortho_pre_vs,
      max_no_of_ortho_post_vs
    )
}

kable(model_post_vs_table_with_different_amount_of_ortho_pre_and_post_vs_Model2, row.names = T) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")


no_orto_in_model_pre_vs_and_in_model_post_vs_with_max_Q2_and_diff_less_than_02 <-
  selecting_model_with_diff_less_than_02_max_Q2_low_pperm_and_few_orthogonals(
    model_post_vs_table_with_different_amount_of_ortho_pre_and_post_vs_Model2, prefered_pR2_and_pQ2_permutated_post_vs
  )
```


#### Plot of model post variable selection with different amount of orthogonal variables in model pre variable selection and in model post variable selection showing difference between R2Y(cum) and Q2(cum) versus Q2(cum)
labels show amount of latent orthogonal variables in model (original,post variable selection)

```{R plot table of orthogonals Model2}

plotof_model_post_vs_table_with_different_amount_of_ortho_pre_and_post_vs(
  model_post_vs_table_with_different_amount_of_ortho_pre_and_post_vs_Model2, no_orto_in_model_pre_vs_and_in_model_post_vs_with_max_Q2_and_diff_less_than_02
)
```

`r no_orto_in_model_pre_vs_and_in_model_post_vs_with_max_Q2_and_diff_less_than_02$"ortho pre v.s."` orthogonal latent variables in model pre variable selection and `r no_orto_in_model_pre_vs_and_in_model_post_vs_with_max_Q2_and_diff_less_than_02$"ortho post v.s."` in model post variable selection give model post variable selection with highest Q2 and lowest R2-Q2.

```{R}
ortho_pre_vs <- no_orto_in_model_pre_vs_and_in_model_post_vs_with_max_Q2_and_diff_less_than_02$"ortho pre v.s."

ortho_post_vs <- no_orto_in_model_pre_vs_and_in_model_post_vs_with_max_Q2_and_diff_less_than_02$"ortho post v.s."
ortho_pre_vs_Model2 <- ortho_pre_vs
ortho_post_vs_Model2 <- ortho_post_vs
```


## Best performing model using p(corr) cutoff corresponding to userset pvalue cutoff
### Model description
#### Best performing model performing variable selection using p(corr) cutoff `r pcorr` corresponding to p-value `r p_pearson_of_pcorr_cutoff` has `r ortho_pre_vs` orthogonal in model pre variable selection and `r ortho_post_vs` orthogonal in model post variable selection

```{R Best performing model2}

testvariablename <- "result_Model2"
testvariable <- exist_in_rdata(testvariablename, filename_rdata, directory_output_reports, directory_and_filename_rdata)
if (!is.null(testvariable)) {
  result_Model2 <- testvariable
} else {
  result_Model2 <-
    opls_model_with_variable_selection_trycatch(
      subsetdatamatrix,
      ortho_pre_vs,
      ortho_post_vs,
      class = classordered,
      pcorr, printoptmodel = "none",
      plotoptmodel = "none",
      no_permutations_post_vs = no_permutations_post_vs_selected_models,
      variable_selection_using_VIP,
      max_no_of_ortho_pre_vs,
      max_no_of_ortho_post_vs
    )
}
```
### Model pre variable selection

```{R plot model pre vs model2}
result_pre_vs <- result_Model2$beforevsdata.oplsda@summaryDF
colnames(result_pre_vs)[6] <- "ortho pre v.s."
kable(result_pre_vs, row.names = T) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

plot(result_Model2$beforevsdata.oplsda, typeVc = c("overview"))
```

### Model statistics

```{R plot summary model2}

kable(result_Model2$resultaftervs, row.names = T) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

plot(result_Model2$aftervsdata.oplsda, typeVc = c("overview"))
if (ortho_post_vs > 0) {
  plot(result_Model2$aftervsdata.oplsda, typeVc = c("outlier"))
}
```

### Score plots

```{R plot score model2}

if (ortho_post_vs > 0) {
  plot(result_Model2$aftervsdata.oplsda, typeVc = c("x-score"))
}

plotscore(result_Model2, classordered)

plotboxplot(result_Model2, subsetsampleID, colname_groupID, classordered)
```

### Loading plots

```{R plot loading model2}

if (ortho_post_vs > 0) {
  plot(result_Model2$aftervsdata.oplsda, typeVc = c("x-loading"))
}

plotpcorr(result_Model2, variable_names_length, variable_names_position)

if (length(result_Model2$pcorrlistaftervs$pcorrlistaftervs) >= 50) {
  plotpcorronly50variables(result_Model2, variable_names_length, variable_names_position)
}
```

### Permutation after variable selection

```{R plot perm post vs model2}

plot(result_Model2$aftervsdata.oplsda, typeVc = c("permutation"))
```

### Permutation including variable selection
Subjects were permutated and variable selection performed using p(corr) cutoff `r pcorr` corresponding to p-value `r p_pearson_of_pcorr_cutoff`,  with `r ortho_pre_vs` orthogonal in model pre variable selection and `r ortho_post_vs` orthogonal in model post variable selection

#### Table of permutation

```{R permutation over vs Model2}

testvariablename <- "permutated_models_Model2"
testvariable <- exist_in_rdata(testvariablename, filename_rdata, directory_output_reports, directory_and_filename_rdata)
if (!is.null(testvariable)) {
  permutated_models_Model2 <- testvariable
} else {
  permutated_models_Model2 <-
    table_of_randomised_models_over_vs(
      subsetsampleID,
      colname_groupID,
      subsetdatamatrix,
      ortho_pre_vs=NA,
      ortho_post_vs=NA,
      class = classordered,
      pcorr,
      no_permutations_over_vs,
      variable_selection_using_VIP,
      max_no_of_ortho_pre_vs,
      max_no_of_ortho_post_vs
    )
}

for (l in 1:nrow(permutated_models_Model2)) {
  if (is.na(permutated_models_Model2$`Q2(cum)`[l]) | permutated_models_Model2$`Q2(cum)`[l] < (-1)) {
    permutated_models_Model2$`Q2(cum)`[l] <- 0
  }
}

kable(permutated_models_Model2) %>%
  kable_styling() %>%
  scroll_box(width = "fullwidth", height = "300px")
```

 
#### Percentage of R2 and Q2 in permutated model larger than R2 and Q2 in unpermutated model

```{R}

percent_R2_and_Q2_in_permutated_larger_than_in_unpermutated_Model2 <-
  percent_R2_and_Q2_in_permutated_larger_than_in_unpermutated(
    permutated_models_Model2,
    result_Model2$resultaftervs$`R2Y(cum)`,
    result_Model2$resultaftervs$`Q2(cum)`
  )

pvalue_R2_and_Q2_in_perm_Model2 <-
  pvalue_R2_and_Q2_in_perm(
    permutated_models_Model2,
    result_Model2$resultaftervs$`R2Y(cum)`,
    result_Model2$resultaftervs$`Q2(cum)`
  )

percentage_and_pvalue_perm_Model2 <- as.data.frame(cbind(percent_R2_and_Q2_in_permutated_larger_than_in_unpermutated_Model2, row.names(pvalue_R2_and_Q2_in_perm_Model2), pvalue_R2_and_Q2_in_perm_Model2[, 1]))

colnames(percentage_and_pvalue_perm_Model2) <- NULL
kable(percentage_and_pvalue_perm_Model2, row.names = T) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```
#### Plot permutations of best performing model with variable selection using p(corr) cutoff `r pcorr` corresponding to p-value `r p_pearson_of_pcorr_cutoff`

```{R  plot permutation over vs model2, fig.width = 10}

plotpermutationswithoriginalmodelandreg(permutated_models_Model2, subsetdatamatrix, ortho_pre_vs, ortho_post_vs, class = classordered, pcorr, variable_selection_using_VIP, max_no_of_ortho_pre_vs, max_no_of_ortho_post_vs)
```


### ROC curve
Confidence intervals through 2000 stratified bootstrap replicates

```{R}

pROC_Model2 <- roc(classordered, result_Model2$scoreofvariablesaftervs[, 1],
  smoothed = TRUE,
  ci = TRUE, stratified = T,
  plot = TRUE, auc.polygon = TRUE, max.auc.polygon = TRUE, grid = TRUE,
  print.auc = TRUE, show.thres = T
)
sens.ci <- ci.se(pROC_Model2)
plot(sens.ci, type = "shape", col = "lightblue")

data_to_evalmod <- mmdata(scores = result_Model2$scoreofvariablesaftervs, labels = classordered)
precrec_Model2 <- evalmod(data_to_evalmod, mode = "basic")
autoplot(precrec_Model2)

```
